<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIzwof4m\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIzwof4m/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIzwof4m.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerIzwof4m\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerIzwof4m\appProdProjectContainer([
    'container.build_hash' => 'Izwof4m',
    'container.build_id' => 'b6dc3a29',
    'container.build_time' => 1596730896,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIzwof4m');
